### PR TITLE
changed the font

### LINKED ISSUE #32: Fix Typography on home page of website
File to be changed: [banner1](https://github.com/RoboticsClubIITJ/web-portal/blob/master/frontend/src/components/home/Banner1.vue)

### PR DESCRIPTION
**Pull request by hiteshidudeja**
closes #32 
Changed the font

### CODE REVIEW

**Comment by manav1403** [comment]
@hiteshidudeja pls added screenshots of the UI changes
and also mention closes #<issue number> in pr description

**Comment by DarshitJain04** [comment]
> Changed the font

@hiteshidudeja add relevant screenshots so that we can review and merge your PR :)

**Comment by DarshitJain04** [comment]
> > Changed the font
> 
> @hiteshidudeja add relevant screenshots so that we can review and merge your PR :)
> Also pull changes from the master before pushing

@hiteshidudeja ?

**Comment by hiteshidudeja** [comment]
@DarshitJain04 
image

**Comment by manav1403** [comment]
@hiteshidudeja can you send a screenshot of the mobile view as well

**Comment by hiteshidudeja** [comment]
image
@manav1403

**Comment by hiteshidudeja** [comment]
Untitled

@manav1403

**Review by manav1403 — APPROVED** [review]

**Comment by manav1403** [comment]
@hiteshidudeja  thanks for your contribution
Great Work!

**Pull request merged**
